### PR TITLE
Implemented Boss export feature

### PR DESCRIPTION
**Pull request by Mytrin**
Created singleton for serializing to JSON. 
Also added button with simple export method call to MainForm.

### CODE REVIEW

**Comment by rodi0878** [comment]
I'm missing unit tests for this new feature.

**Comment by Mytrin** [comment]
Done. 

I have also noticed that _JsonSerializer_ can not serialize _HashSet_ and therefore **Boss** was exported without his **Employee**s. I managed to find more appropriate class. However, I would recommend using Json.NET framework in future, in case you plan more complex data objects.

**Comment by Mytrin** [comment]
Sorry, it's hard to write tests when my VS ignores NUnit tests even after plugin reinstallation.

**Comment by rodi0878** [comment]
Did you tested also a case with nesting? Eg Boss a -> Boss b -> Employee c

**Comment by rodi0878** [comment]
It looks ok, please update patch for latest revision. Thank you

**Pull request merged**
