### PR TITLE
Added a double-click feature

### PR DESCRIPTION
**Pull request by machovec**
Added a double-click feature on listbox of bosses.

### CODE REVIEW

**Comment by rodi0878** [comment]
What happens if you click into blank space of listbox?

**Comment by machovec** [comment]
Shows dialog select boss
image

**Comment by rodi0878** [comment]
Yes and I would prefer not to annoy user with error dialog on doubleclick to empty space.

**Comment by rodi0878** [comment]
It looks nice, could you please update patch for conflictless merging? Thank you

**Comment by machovec** [comment]
Fixed conflicts.

**Pull request merged**
